server.port = 8080

server.contextPath=/demo_res_owms
security.basic.enabled=false
server.session.timeout=1800
spring.main.banner-mode=off

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.location=C:/uploads/tmp
spring.devtools.restart.enabled=false
# MySql settings

#spring.datasource.url=jdbc:mysql://172.18.210.16:3306/res_owms_prod_27oct25?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectionCollation=utf8mb4_unicode_ci
#spring.datasource.username=res_usr
#spring.datasource.password=res@2026!

spring.datasource.url=jdbc:mysql://172.18.200.168:3306/res_owms_prod_27oct25?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=res_usr
spring.datasource.password=res!#0909

# new staging 172.18.210.16
#spring.datasource.url=jdbc:mysql://10.115.253.116:3306/res_owms_prod_27oct25?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#spring.datasource.username=root
#spring.datasource.password=Mp$@d(coe$t@g!ng#2024-25

#spring.datasource.url=jdbc:mysql://localhost:3306/res_owms_prod?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#spring.datasource.username=root
#spring.datasource.password=rootwdp


#spring.datasource.url=jdbc:mysql://172.18.200.168:3306/res_owms_prod_29aug23?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

#spring.datasource.url=jdbc:mysql://10.115.253.116:3306/res_owms_prod_29aug23?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

#spring.datasource.username=root
#spring.datasource.password=Mp$@d(coe$t@g!ng#2024-25

#spring.datasource.url=jdbc:mysql://164.100.196.217:3306/demo_res_owms_prod?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8
#spring.datasource.url=jdbc:mysql://10.115.96.111:3306/res_owms_live_230221?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8
#spring.datasource.url=jdbc:mysql://localhost:3306/res_owms?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8

#spring.datasource.url=jdbc:mysql://10.115.96.111:3306/res_owms_prod_10022020?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#spring.datasource.url=jdbc:mysql://10.115.253.116:3306/res_owms_prod?createDatabaseIfNotExist=true&useSSL=false&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate properties for show sql with parameters in the console
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.properties.hibernate.type=trace
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=false

#envers properties
#spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_AUD
#spring.jpa.properties.org.hibernate.envers.revision_field_name=REVISION_ID
#spring.jpa.properties.org.hibernate.envers.revision_type_field_name=REVISION_TYPE
#spring.jpa.properties.org.hibernate.envers.global_with_modified_flag = true


# Number of ms to wait before throwing an exception if no connection is available.
spring.datasource.tomcat.max-wait=10000

# Maximum number of active connections that can be allocated from this pool at the same time.
spring.datasource.tomcat.max-active=50

# Validate the connection before borrowing it from the pool.
spring.datasource.tomcat.test-on-borrow=true

logging.level.org.springframework.web=ERROR
logging.level.com.res=INFO

# Logging pattern for the console
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Logging pattern for file
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.file=D:/Applications/logs/demo_res_owms.log

spring.http.multipart.max-file-size=5MB
spring.http.multipart.max-request-size=5MB

#Email Account Details
mail.smtp.host=email.gov.in
mail.smtp.port=465
mail.from=RES Admin
mail.username=res.owms@mp.gov.in
mail.password=Res13$Res13

#SMS Account Details
#sms.userName=resdmp_api
#sms.password=resdmp@123
sms.userName=DITMP-RESDMP
sms.password=Res14$Res14
sms.senderId=RESDMP
sms.url=https://msdgweb.mgov.gov.in/esms/sendsmsrequestDLT
#sms.url=http://digimate.airtel.in:15181/BULK_API/SendMessage
#sms.url=https://digimate.airtel.in:25443/BulkPush/DigimateCurl
sms.secureKey=db7c00c3-42cc-4f63-9117-a155eb0a8cde
sms.dltTmId=1001096933494158
sms.campName=resdmp_api
sms.dltPeid=1001403036063563562


document.root=D:/DEMO_RES_DOCS/
document.work=WORK/WORK_DOCS/
document.technical=WORK/TECH_DOC/
document.administration=WORK/ADMS_DOC/
document.workRequisition = WORK/WORK_REQ_DOC/
document.inspectionPath = WORK/BILL_INSP/
document.ccFilePath = WORK/CC_FILE/
document.inspectionPathCC  = WORK/BILL_INSP/CC/
document.inspectionPathSqmImage = WORK/SQM_INSP_IMAGE/
document.inspectionPathOfficerImage = WORK/OFFICER_INSP_IMAGE/
document.inspectionPathSqmFile = WORK/SQM_INSP_FILE/
document.inspectionPathOfficerFile = WORK/OFFICER_INSP_FILE/

document.WorkMasterKmlFilePath=WORK/KML_WORK_LOCATION_FILE/

#applicationDeploymentServerName=10.115.96.111
#applicationDeploymentServerName=localhost
applicationDeploymentServerName=raman-coe.mapit.gov.in

#host.ip.address = http://10.115.96.111:8050
#host.ip.address = http://10.125.242.78:8060
host.ip.address = http://raman-coe.mapit.gov.in
#host.ip.address = http://164.100.196.217:8080


